project:
  type: website
  output-dir: docs

website:
  title: "Lindsay Katz"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - contact.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



